Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    config.vm.box = "ubuntu/focal64"
    vm1.vm.network "public_network", ip:"10.10.10.11"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  
    vm1.vm.provision "shell" , path: "provision.sh"
  end

end
